### PR TITLE
Made the Shaders force it to work !!!

### PR DESCRIPTION
**Pull request by JonnycatMeow**
this will help shaders work on windows,mac,linux,android and even html5!!!!

### CODE REVIEW

**Comment by ItsyourboyJonnycat** [comment]
@notweuz please merge this

**Comment by ItsyourboyJonnycat** [comment]
here is a gameplay video of it working

**Comment by ItsyourboyJonnycat** [comment]
and if it does lag with the shaders i recommend 60 fps

**Comment by JonnycatMeow** [comment]
noooo i made a mistake

**Pull request closed without merging**
